#!/bin/sh

version=1.0.0

install() {
    cd /tmp && curl -k -o shadow.sh https://raw.githubusercontent.com/qiwihui/hiwifi-ss/master/shadow.sh && sh shadow.sh && rm shadow.sh
    if [ $? -ne 0 ];then
        return 1
    fi

    # web安装界面的参数会保存到文件，这里引用参数文件，即可使用变量
    . ./soho-to-intranet.conf
    uci set shadowsocks.shadowsocks.timeout="$timeout"
    uci set shadowsocks.shadowsocks.enable="$enable"
    uci set shadowsocks.shadowsocks.server_port="$server_port"
    uci set shadowsocks.shadowsocks.method="$method"
    uci set shadowsocks.shadowsocks.dnsserver="$dnsserver"
    uci set shadowsocks.shadowsocks.password="$password"
    uci set shadowsocks.shadowsocks.server="$server"
    uci set shadowsocks.shadowsocks.defaultroute="$defaultroute"
    uci commit
 
    start
    set_dns

    return 0
}

uninstall() {
    stop
    opkg remove geewan-ss
    return 0
}

start() {
    /etc/init.d/gw-shadowsocks start >/dev/null 2>&1
    return 0
}

stop() {
    /etc/init.d/gw-shadowsocks stop >/dev/null 2>&1
    return 0
}

status() {
    local stat=running

    pgrep /usr/bin/ss-local >/dev/null 2>&1
    CODE="$?"

    [ "$CODE" -ne "0" ] && {
        stat=stopped
    }

    echo "{ \"status\" : \"$stat\" }"
    return 0
}

set_dns() {
    #使用自定义dns，不要使用运营商dns，否则会出现dns广告而且有些国内域名都无法解析
    echo "set_dns start"
    uci delete network.wan.dns >/dev/null 2>&1
    uci set network.wan.peerdns=0
    uci add_list network.wan.dns="119.29.29.29"
    uci add_list network.wan.dns="223.5.5.5"

    #极路由的界面读取tnetwork的配置，所以也设置一下
    uci set tnetwork.@defaults[0].peerdns=0
    uci set tnetwork.@defaults[0].override_dns="119.29.29.29"
    uci set tnetwork.@defaults[0].override_dns2="223.5.5.5"
    uci commit
    /etc/init.d/network reload
    echo "set_dns end"
    return 0
}
